// Mock data for the table
export const mockPieces = [
    {
        id: '1',
        title: 'Aba-frente-americano-linho-azul_marinho',
        sku: '#123',
        type: 'Americano',
        displayOrder: 5,
        status: 'Ativo' as const,
    },
    {
        id: '2',
        title: 'Aba-frente-americano-linho-azul_marinho',
        sku: '#123',
        type: 'Americano',
        displayOrder: 5,
        status: 'Ativo' as const,
    },
    {
        id: '3',
        title: 'Aba-frente-americano-linho-azul_marinho',
        sku: '#123',
        type: 'Americano',
        displayOrder: 5,
        status: 'Ativo' as const,
    },
    {
        id: '4',
        title: 'Aba-frente-americano-linho-azul_marinho',
        sku: '#123',
        type: 'Americano',
        displayOrder: 5,
        status: 'Ativo' as const,
    },
    {
        id: '5',
        title: 'Aba-frente-americano-linho-azul_marinho',
        sku: '#123',
        type: 'Americano',
        displayOrder: 5,
        status: 'Ativo' as const,
    },
    {
        id: '6',
        title: 'Aba-frente-americano-linho-azul_marinho',
        sku: '#123',
        type: 'Americano',
        displayOrder: 5,
        status: 'Ativo' as const,
    },
    {
        id: '7',
        title: 'Aba-frente-americano-linho-azul_marinho',
        sku: '#123',
        type: 'Americano',
        displayOrder: 5,
        status: 'Ativo' as const,
    },
    {
        id: '8',
        title: 'Modelo São Paulo',
        sku: '#123',
        type: 'Americano',
        displayOrder: 5,
        status: 'Ativo' as const,
    },
    {
        id: '9',
        title: 'Modelo São Paulo',
        sku: '#123',
        type: 'Americano',
        displayOrder: 5,
        status: 'Ativo' as const,
    },
    {
        id: '10',
        title: 'Modelo São Paulo',
        sku: '#123',
        type: 'Americano',
        displayOrder: 5,
        status: 'Ativo' as const,
    },
];
